---
- name: APT | update repo cach
  apt:
    update_cache: yes
  tags:
    - done

- name: Readmine. Install packages
  apt:
    name: "{{ apt_redmine_packages }}"
    state: latest
  tags:
    - done

- name: MySQL. Install and setup
  block:
  - template:
      src: .my.cnf
      dest: ~/.my.cnf
      owner: root
      mode: 0600
  - service:
      name: mysql
      state: started
      enabled: yes
  tags:
    - done

- mysql_db:
    name: "{{ app_db_name }}"
    encoding: utf8

- mysql_user:
    name: "{{ app_db_user }}" 
    password: "{{ app_db_pass }}"
    priv: "{{ app_db_name }}.*:ALL"
