---
- name: APT | update repo cach
  apt:
    update_cache: yes
  tags:
    - done

- name: Readmine. Install packages
  apt:
    name: "{{ apt_redmine_packages }}"
    state: latest
  tags:
    - done

- name: MySQL. Install and setup
  block:
  - template:
      src: .my.cnf
      dest: ~/.my.cnf
      owner: root
      mode: 0600
  - service:
      name: mysql
      state: started
      enabled: yes
  tags:
    - done

- name: MySQL DB
  mysql_db:
    name: "{{ app_db_name }}"
    encoding: utf8
  tags:
    - done
- name: Create MySQL DB
  mysql_user:
    name: "{{ app_db_user }}" 
    password: "{{ app_db_pass }}"
    priv: "{{ app_db_name }}.*:ALL"
<<<<<<< HEAD
  tags:
    - done

- name: Readmine. Clone repository
  git: 
    repo: "{{ app_repo }}" 
    dest: "{{ app_home }}" 
    version: '{{ app_version }}' 
    accept_hostkey: yes

- name: Redmine. Change permissions
  file:
    path: "{{ app_home }}/public"
    owner: www-data
    group: www-data
    recurse: yes

- name: Redmine. Change permissions
  file:
    path: "{{ app_home }}/tmp"
    mode: 777
    recurse: yes
=======
>>>>>>> 7cba9800946d0b201b5334fd10acc42ec7cab007
